Feature/31 us10 organizacao de menu lateral colapsavel
fga-eps-mds/2023-1-MeasureSoftGram-Front pull request #8
Opened 2023-05-27 03:02 UTC by SwampTG

## Motivação

## Mudanças

- Algo que adicionou/mudou/consertou

## Status Checklist

- [ ] Test
- [ ] Lint
- [ ] Development

## Screenshots

| Before                                               | After                                                |
| ---------------------------------------------------- | ---------------------------------------------------- |
| <img src="https://via.placeholder.com/100x80.png" /> | <img src="https://via.placeholder.com/100x80.png" /> |

## Execução

- Acesse a página url /dashboard

2023-05-29 12:31 UTC, CarlosFiuza requested changes

2023-05-29 12:31 UTC, CarlosFiuza commented on src/shared/components/Layout/SideMenu/SideMenuWrapper/SideMenuWrapper.tsx
> +      <Link href="/products">
Ao clicar na logo deveria redirecionar para a tela home.

2023-05-29 19:43 UTC, higton submitted a review, later dismissed
A pipeline do Sonarcloud está falhando. Precisa aumentar a cobertura dos testes e consertar os bugs.

2023-06-13 17:36 UTC, CarlosFiuza approved these changes

2023-06-14 01:43 UTC, merged